name: Build, publish and deploy project to Simply

on: [push]

jobs:
  build_and_deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 8.0
          
      - name: Install dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish
        
      - name: Test with .NET
        run: dotnet test

      - name: Deploy to Simply        
        uses: talunzhang/SmarterASP.NET-web-deploy@v1.0.1
        with:
          website-name: yanaye3635-001-site1
          server-computer-name: https://win5187.site4now.net:8172
          server-username: yanaye3635-001
          server-password: Phuoc123@
          source-path: '\artifacts\publish\net5.0\release\'
