name: Build, publish and deploy project to Simply

on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: 5.0

jobs:
  build_and_deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup .NET 5
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Install dependencies
        run: dotnet restore
        
      - name: Build app
        run: dotnet build --configuration Release --no-restore
                
      - name: Test with .NET
        run: dotnet test

      - name: Publish app
        run: dotnet publish --configuration Release --output ./publish --no-build

      - name: Deploy to Simply        
        uses: talunzhang/SmarterASP.NET-web-deploy@v1.0.1
        with:
          website-name: ${{ secrets.WEBSITE_NAME }}
          server-computer-name: ${{ secrets.SERVER_COMPUTER_NAME }}
          server-username: ${{ secrets.SERVER_USERNAME }}
          server-password: ${{ secrets.SERVER_PASSWORD }}
          source-path: '\publish\'
